name: CI - Podman Build and Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: self-hosted  # ← 중요: 로컬 runner 지정

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Login to Quay
        run: |
          podman login --tls-verify=false quay-quay-quay-enterprise.apps-crc.testing \
            -u ${{ secrets.QUAY_USERNAME }} \
            -p ${{ secrets.QUAY_PASSWORD }}

      - name: Build and Push with Podman
        run: |
          podman build -t quay-quay-quay-enterprise.apps-crc.testing/admin/myapp:v2.0 .
          podman push --tls-verify=false quay-quay-quay-enterprise.apps-crc.testing/admin/myapp:v2.0
